    <meta charset="UTF-8">
    <style type="text/css">
        html, body {
            margin: 0;
            padding: 0;
        }

        * {
            box-sizing: border-box;
        }

        .slider {
            width: 50%;
            margin: 100px auto;
        }

        .slick-slide {
            margin: 0px 20px;
        }

        .slick-slide img {
            width: 100%;
        }

        .slick-prev:before,
        .slick-next:before {
            color: black;
        }


        .slick-slide {
            transition: all ease-in-out .3s;
            opacity: .2;
        }

        .slick-active {
            opacity: .5;
        }

        .slick-current {
            opacity: 1;
        }
    </style>

<?php

try {
    $_productCollection = Mage::getModel('catalog/product')
        ->getCollection()
        ->addAttributeToSort('created_at', 'DESC')
        ->addAttributeToSelect('*')
        ->addAttributeToFilter('display_on_homepage', 1)    ;
} catch (Exception $e) {
    echo '<pre>';
    var_dump($e->getMessage());
    echo '</pre>';
    die;
}
?>
<section class="regular slider">
    <?php foreach ($_productCollection as $product):?>
    <div>
        <img src="http://placehold.it/350x300?text=<?php echo $product->getId(); ?>">
        <a href="<?php echo $product->getProductUrl() ?>"><?php echo $product->getName()?></a>

    </div>  <?php endforeach; ?>

</section>

<!--<script src="https://code.jquery.com/jquery-2.2.0.min.js" type="text/javascript"></script>-->
<!--<script src="./slick/slick.js" type="text/javascript" charset="utf-8"></script>-->


<script type="text/javascript">
    // clicked = true;
    $( document ).ready(function($) {
        console.log(123);
        $(".regular").slick({
            dots: true,
            infinite: true,
            slidesToShow: 3,
            slidesToScroll: 3
        });


    });
</script>

