
<style type="text/css">
        img {
            width: 200px;
            height: 200px;
        }
        .list {
            display:inline-block;
        }
</style>


<?php
$collection = $this->getExtensionCollection();
?>

<?php foreach ($collection as $value):?>
<div class="list">
    <>
    <div class="title"> <?php echo $value->getTitle()?></div>
        <img id="test" src="<?php echo $value->getImage();?>"><br>
    <div class="description"><?php echo $value->getShortDescription()?></div>
</div>
<?php endforeach;?>






